import { useEffect, useState, useMemo } from "react";
import { io } from "socket.io-client";
import { Container, Input, Button, Stack, Box, Text } from "@chakra-ui/react";
import Head from "next/head";

interface IChat {
  user: string;
  msg: string;
}

let socket: any = null;
export default function Home() {
  const [input, setInput] = useState("");
  const [chat, setChat] = useState<IChat[]>([]);
  const [connected, setConnected] = useState<boolean>(false);
  const [id, setId] = useState("");

  const socketInitializer = async () => {
    await fetch("/api/socket");
    socket = io();
    socket.on("connect", () => {
      console.log("connected", socket.id);
      setConnected(true);
      setId(socket.id);
    });

    socket.on("update-input", (msg: { id: string; input: string }) => {
      setChat((e) => [...e, { msg: msg.input, user: msg.id }]);
    });

    if (!connected) {
      socket.on("disconnect"),
        () => {
          console.log("disconnect bos");
        };
    }
  };

  useEffect(() => {
    if (socket) return;
    socketInitializer();
  }, []);

  const onChangeHandler = (e: any) => {
    setInput(e.target.value);
  };

  const sendChat = () => {
    socket.emit("input-change", { input, id });
    setInput("");
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack height={"80vh"} overflowY="auto" mt="5rem">
        {chat.length
          ? chat.map((item, idx) => (
              <Text key={idx}>
                id: {item.user} - {item.msg}
              </Text>
            ))
          : "No Message"}
      </Stack>
      <Stack direction="row">
        <Input
          placeholder={connected ? "typing something..." : "connecting"}
          type="text"
          value={input}
          onChange={onChangeHandler}
          onKeyPress={(e) => {
            if (e.key === "Enter") {
              sendChat();
            }
          }}
        />
        <Button onClick={sendChat}>Send</Button>
      </Stack>
    </Container>
  );
}
